### ISSUE TITLE
No Master quality support

### ISSUE THREAD

**Issue by Moresteck** [Mastermindzh/tidal-hifi#65] opened 2021-09-19 14:23 UTC
I can only go as high as HIFI on the scale, despite the project being called "tidal-hifi" which implies Tidal Hi-Fi support.
It's no different than what I get in the browser.

**Comment by Mastermindzh** [comment] 2021-09-19 15:35
Master quality is only available on official apps.
This is not an official app. That's why it's called tidal-hifi instead of tidal-master. Many browsers don't come with support for hifi due to the lack of widevine.

All of this is described in the README, should you want more info.

Duplicate of [#30](https://github.com/Mastermindzh/tidal-hifi/issues/30)

**Closed by Mastermindzh** 2021-09-19 15:35 UTC
