### ISSUE TITLE
TIDAL Hifi cannot launch

### ISSUE THREAD

**Issue by bjornpijnacker** [Mastermindzh/tidal-hifi#147] opened 2022-06-14 12:51 UTC
Since earlier today the following error is shown when trying to launch tidal-hifi on the newest version:

![image](https://user-images.githubusercontent.com/35508080/173581305-63753066-46a4-4714-bfb5-a30d90a82bf0.png)

<hr />

**Edit by mastermindzh**:

Everything that we've seen points to this being an upstream issue (meaning Tidal broke it, not us).
There is a simple fix that will solve this (and some other upstream issues) with relative ease:

1. Quit tidal-hifi
2. Remove everything from the `~/.config/tidal-hifi` directory except  "config.json". In bash inside the directory: `rm -rfv !(config.json)`
3. Try and start the app again
4. If that didn't help, delete the files again and reinstall Tidal-hifi

**Comment by AiyionPrime** [comment] 2022-06-14 14:33
Same here.

**Comment by lolrepeatlol** [comment] 2022-06-14 19:58
This issue occurs even on TIDAL's own desktop app. It's something on TIDAL's end

**Comment by Valoriks** [comment] 2022-06-15 11:04
I fixed it by uninstalling the package, deleting '~/.config/tidal-hifi' folder and by installing the package again. It works for me now.

**Comment by AiyionPrime** [comment] 2022-06-15 12:16
Just deleting `~/.config/tidal-hifi/` was not enough, but what @Valoriks suggested did work for me as well.

**Comment by bjornpijnacker** [comment] 2022-06-15 12:19
Yes, works perfectly.

**Comment by AiyionPrime** [comment] 2022-06-15 12:31
Well, not sure if reinstalling is the solution that should close this issue, as we rather mitigated than resolved the issue, or?

**Comment by bjornpijnacker** [comment] 2022-06-15 14:24
While I agree, @lolrepeatlol already named that this isn't just TIDAL HiFi, so I closed it. I'll reopen it for visibility at least. I think that's a good idea

**Comment by bjornpijnacker** [comment] 2022-06-15 14:34
I tried reinstallation/updating before opening the issue. It didn't help in my case

**Comment by AiyionPrime** [comment] 2022-06-15 14:40
@Mastermindzh I find it interesting that the 'fix' is the same as for #111 back then.
Any ideas which caches or configs should save before applying the fix and possibly send to you for reproduction-purposes?
Or which not to send (thinking about credentials).

**Comment by Mastermindzh** [comment] 2022-06-15 14:52
Tidal-hifi only has a single config file and it only holds information about settings.

All the others are from chromium.

From what it sounds like it might be some cache issue on the side of Tidal/browser. We could preemptively clear parts of the cache but we would have to know which ones.

I'm not sure there is an access token in the config (I haven't checked). But there's probably some kind of auth and refresh token. Both of which should expire with time and shouldn't contain any sensitive info (apart from a name, maybe an email address).

Zipping the config directory and sending it after a  week or so shouldn't be an issue. 

It can go to my private email instead of as an attachment just in case it does contain something I'd you'd like 😄 

Again, no clue because I haven't checked, but it seems likely Tidal uses JWT tokens. If so you can use JWT.io to see what is in the token before sending it.

**Comment by leifdenby** [comment] 2022-06-16 08:27
Reinstalling flatpak didn't work for me either. I've logged it with TIDAL support, hopefully they'll fix it. I don't really want to go back to Spotify, but their linux support is a lot better.

**Comment by lolrepeatlol** [comment] 2022-06-17 02:27
> Reinstalling flatpak didn't work for me either. I've logged it with TIDAL support, hopefully they'll fix it. I don't really want to go back to Spotify, but their linux support is a lot better.

totally feel the same way :/

**Comment by GregStroot** [comment] 2022-06-21 18:20
> Whoever encounters this next, it might be interesting to know, whether deleting the config folder is necessary, or if it's just the re-installation, that "fixes" the screen.

I just encountered this issue. I tried re-installing, accessed via AUR, but that didn't work. @Valoriks suggestion did work

I hope we can keep this in working order, it would be a bummer to have to use the browser. Happy to help if there are actionable items

**Comment by autumn-puffin** [comment] 2022-06-22 10:47
I've encountered this too, after a bit of trial and error it looks like the problem's something in my `tidal-hifi/Service Worker` folder, though I'm finding it hard to narrow it down much more than that, attaching a zip of it since I'm pretty sure it doesn't have any tokens
[tidal-hifi.zip](https://github.com/Mastermindzh/tidal-hifi/files/8956863/tidal-hifi.zip)

**Comment by palich2000** [comment] 2022-07-04 14:36
Same here. 
In this app and in Chrome browser.

**Comment by Mastermindzh** [comment] 2022-07-04 15:00
Oh... I forgot to reply. My bad.

The problem does indeed seem to be related to service workers. Thanks @autumn-puffin.
Removing the config directory (the fix described above) should work because Tidal would re-install (instead of update) at that point which doesn't seem to have any issues.

The only thing we can really do is try and detect the error and "handle" it... something like:

- detect error message
- remove all chrome temp files
- tell user to restart
- profit?

But that isn't very clean.... especially because it's an upstream issue.
I'll keep an eye on it. But I don't know if I will ever get around to fixing it if I'm honest... it's very hard to reproduce on my own.

I'll try and make it clear that the issue exists and how to fix it for now.
Thanks!

**Comment by palich2000** [comment] 2022-07-05 07:10
I have debian 10.
This problem does not disappear in my tidal-hifi, whether I delete the config or not, it does not affect. The problem remains.
I installed tidal-hifi after their native web player stopped working with a paid subscription. As it turned out, the native tidal web player does not work in windows either. I connected via vpn and that didn't help either.
It seems to me that they just turned off the web player. Well, at least for me :)

**Comment by Mastermindzh** [comment] 2022-07-07 07:28
Thanks for the reply @palich2000.

Turns out that the issue is much bigger than initially thought.... we now have reports from the 2 official platforms (both Mac and Windows) not working either... there's something really messed up with the Tidal web player unfortunately!

**Comment by api-haus** [comment] 2023-01-15 03:22
@palich2000 Kind of weird that this happening. I only had English and Ukrainian localizations and this affected me as well, until I've set the language and locale env.

**Comment by palich2000** [comment] 2023-01-15 09:43
Maybe geolocation works.
This happens to me every month, usually after the next payment.
My solution works successfully.

cd ~
rm -rf .config/tidal-hifi/
LANGUAGE=en LANG=en_US.UTF-8 tidal-hifi

**Comment by Mastermindzh** [comment] 2023-02-02 21:47
Closing with a fix/workaround: https://github.com/Mastermindzh/tidal-hifi/wiki/Known-issues---workarounds#2-tidal-hifi-cant-launch--browser-incompatible

**Closed by Mastermindzh** 2023-02-02 21:47 UTC
Labels: bug, Fixed with workaround, Tidal-upstream issue
