### ISSUE TITLE
Tidal caps at 48khz output

### ISSUE THREAD

**Issue by valimsam** [Mastermindzh/tidal-hifi#499] opened 2024-11-05 14:55 UTC
Even when I set up sound card to 192khz, Tidal app caps at 48khz, Even the song Ozzy Osbourne - Crazy Train having 92khz. At Easyeffects show the app the audio output at 48khz.

![image](https://github.com/user-attachments/assets/65bac5ee-2b6f-4e69-99ef-0d5985974479)
![image](https://github.com/user-attachments/assets/63800aee-f62d-44ae-a487-5b75403a4f00)

**Comment by Mar0xy** [comment] 2024-11-06 11:00
Please check closed issues first or search for the issue first before opening an issue with a repeated question/issue.

Duplicate of: https://github.com/Mastermindzh/tidal-hifi/issues/266

**Closed** 2024-11-07 07:51 UTC
