### ISSUE TITLE
Only plays 48Khz, no matter source sample rate

### ISSUE THREAD

**Issue by PcChip** [Mastermindzh/tidal-hifi#492] opened 2024-10-22 02:08 UTC
on CachyOS, with pipewire configured to allow 44.1, 48, 88.2, 96, and 192 Khz, this app only outputs 48Khz no matter what the input song is  
  
For comparison, if I use FireFox Nightly and play.qobuz.com , it will push the correct sample rate and bitrate to my DAC so there is no resampling

**Comment by Mastermindzh** [comment] 2024-10-23 10:37
Duplicate of: https://github.com/Mastermindzh/tidal-hifi/issues/266

**Closed by Mastermindzh** 2024-10-23 10:37 UTC
