### ISSUE TITLE
please provide a flatpak release

### ISSUE THREAD

**Issue by nthrow** [Mastermindzh/tidal-hifi#125] opened 2022-04-19 21:09 UTC
This is more a release request than an issue - would you please provide a flatpak image as well as a snap?  The design and distribution of snaps is much more centralized, not only requiring official Canonical approval to get into the native repository, but also being incompatible with Linux distributions that don't use systemd (Alpine, Gentoo, Void, etc).  A flatpak image and listing on flathub.org would reach a much larger audience of Linux users currently lacking an option for using the Tidal service.  Thanks for your consideration!

**Comment by Mastermindzh** [comment] 2022-04-20 12:07
Duplicate of #55. Closing.

Hey @nthrow ,

We're working on it 😄. It's nearly finished and we should be able to finish it up pretty quickly.
I will discuss with the others to maybe pick up some extra speed.

Thanks for the inquiry!

**Closed** 2022-04-20 15:14 UTC

**Comment by Mar0xy** [comment] 2022-04-23 10:51
The flatpak is now available on flathub
```sh
flatpak install flathub com.mastermindzh.tidal-hifi
```
https://flathub.org/apps/details/com.mastermindzh.tidal-hifi
