### ISSUE TITLE
Constant 44.1kHz sample rate on Hi & Max

### ISSUE THREAD

**Issue by jmilczak** [Mastermindzh/tidal-hifi#502] opened 2024-11-18 22:13 UTC
I have PC with installed Ubuntu Server 22.04.5 LTS with KDE 5.24.7 GUI.
PC is connected via optical cable to Yamaha R-N602.
Doesn't mater what song is played Hi or Max, sample rate on Yamaha is always 44.1kHz.
Same PC with playing FLAC on Elisa is switching sample rate depending on song quality.
Check this please.

**Comment by Mar0xy** [comment] 2024-11-19 23:11
Duplicate: https://github.com/Mastermindzh/tidal-hifi/issues/266

**Comment by jmilczak** [comment] 2024-11-20 21:52
> Duplicate: #266

It's to complicated for me. Sorry

**Comment by Mastermindzh** [comment] 2024-11-21 11:34
What it kinda boils down to:

- Select a specific HZ you want across all songs
- Force your distro to use that
- Set Tidal to the highest quality

This will upsample or downsample songs to match what you set in your distro instead of playing their native quality.. but.. if the native quality aligns with the sample rate it shouldn't have to do anything and you can enjoy the music as intended.

This is, unfortunately, a limitation we have no idea how to work around as it's in Chrome/Chromium which is used by Electron.

For the rest, yep, duplicate of #266

**Closed by Mastermindzh** 2024-11-21 11:34 UTC
