### ISSUE TITLE
Build for the raspberry pi

### ISSUE THREAD

**Issue by gebim** [Mastermindzh/tidal-hifi#329] opened 2024-01-06 20:18 UTC
if possible (Widevine?). IMHO this would be highly appreciated, as for the pi are numerous high-quality DACs out and CPU-wise a pi4/5 is powerful enough...

**Comment by Mastermindzh** [comment] 2024-02-11 22:25
Won't be available for the forseeable future, see: https://github.com/castlabs/electron-releases/issues/23

**Comment by Mastermindzh** [comment] 2024-04-22 09:21
duplicate of: https://github.com/Mastermindzh/tidal-hifi/issues/329

**Closed by Mastermindzh** 2024-04-22 09:21 UTC
Labels: duplicate, Castlabs upstream issue, cantfix
