### ISSUE TITLE
Launcher icon not showing

### ISSUE THREAD

**Issue by kbasaran** [Mastermindzh/tidal-hifi#117] opened 2022-03-28 20:31 UTC
After installing the snap package in Ubuntu 20.04, I get a launcher which has only a generic icon and not the Tidal icon.

I see that in "/snap/tidal-hifi/x1/meta/gui" there is an "icon.png" and a "tidal-hifi.desktop" file. In the "tidal-hifi.desktop" file it states "Icon=assets/icon.png". Yet there is no "assets" folder.

**Comment by kudos** [comment] 2022-05-02 13:07
There seems to be a similar problem with the RPM, it also points to the same icon path, but the build configuration seems to point to `TIDAL.icns`.

**Comment by maxengel** [comment] 2022-07-12 17:08
I can confirm this is happening with Ubuntu 22.04 when the app is installed via the `.deb` package.

**Comment by Mastermindzh** [comment] 2022-08-07 14:50
Version [4.1.0](https://github.com/Mastermindzh/tidal-hifi/releases/tag/4.1.0) was just released with a fix for this issue 😄

**Comment by kbasaran** [comment] 2022-10-01 07:28
> Version [4.1.0](https://github.com/Mastermindzh/tidal-hifi/releases/tag/4.1.0) was just released with a fix for this issue smile

Please note I still have the issue in 4.2.0, after a snap install.
Ubuntu 22.04.1.

**Comment by Mastermindzh** [comment] 2023-02-02 21:50
The most recent releases have reverted back to the icon strategy from before so this is now fixed.

**Closed by Mastermindzh** 2023-02-02 21:50 UTC
Labels: bug, electron-builder issue
