### ISSUE TITLE
Fail to Open Fedora 39 KDE

### ISSUE THREAD

**Issue by agarlow23** [Mastermindzh/tidal-hifi#408] opened 2024-05-23 02:05 UTC
New install of Fedora 39 on Framework 13 and flatpak won't open. First it complained about not having access to the system bus so I used Flatseal to enable dbus system bus, but it still wont open.

Output of trying to open in terminal with --trace-warnings gives;

UnhandledPromiseRejectionWarning: Error: Failed to install required components
    at n.whenReady (node:electron/js2c/browser_init:2:12873)
    at emitUnhandledRejectionWarning (node:internal/process/promises:200:15)
    at processPromiseRejections (node:internal/process/promises:296:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
(node:2) Error: Failed to install required components
    at n.whenReady (node:electron/js2c/browser_init:2:12873)

System Specs:
OS: Fedora Linux 39 (KDE Plasma) x86_64
Kernel: 6.8.10-200.fc39.x86_64
Shell: fish 3.7.0
DE: KDE Plasma 5.27.11
WM: KWin (X11)
CPU: 11th Gen Intel(R) Core(TM) i7-1165G7 (8) @ 4.70 GHz
GPU: Intel Iris Xe Graphics

**Comment by crimsonthunder** [comment] 2024-06-02 16:56
Same Error for me. Latest Flatpak-Version.

Wayland socket not available, running through Xwayland.
(node:2) UnhandledPromiseRejectionWarning: Error: Failed to install required components
    at n.whenReady (node:electron/js2c/browser_init:2:12873)
    at emitUnhandledRejectionWarning (node:internal/process/promises:200:15)
    at processPromiseRejections (node:internal/process/promises:296:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
(node:2) Error: Failed to install required components
    at n.whenReady (node:electron/js2c/browser_init:2:12873)

System:
OS: openSUSE Tumbleweed 20240524 x86_64
Kernel: Linux 6.9.1-1-default
Shell: zsh 5.9
Display (LC32G7xT): 2560x1440 @ 144H
DE: KDE Plasma 6.0.4
WM: KWin (Wayland)
Theme: Breeze (openSUSEdark) [QT], Breeze-Dar]
CPU: AMD Ryzen 9 3900X (24) @ 4,40 GHz
GPU: AMD Radeon RX 7900 XTX @ 0,02 GHz
Memory: 31,26 GiB

**Comment by Mastermindzh** [comment] 2024-06-04 07:20
Did you try the other installs to narrow down whether it's an app problem or a packaging problem?
Haven't gotten complaints on this from others tbh 😄

**Comment by crimsonthunder** [comment] 2024-06-04 09:07
Iam on vacation right now. Will test it when I get home.

Rick van Lieshout ***@***.***> schrieb am Di., 4. Juni 2024,
09:21:

**Comment by Mar0xy** [comment] 2024-06-04 21:40
>  packaging problem?

Would be very weird for it to be a packaging problem considering this started happening to fresh flatpak users on 5.13.0 while all versions before were fine.

**Comment by crimsonthunder** [comment] 2024-06-10 17:25
Tried this package (non flatpak) and got the same problem:
https://build.opensuse.org/package/show/home:Maroxy/tidal-hifi

I manually installed older FlatPak packages (oldest version February).
I get the same error message with all variants. Unfortunately I can't take much from it and am now at a loss.

**Comment by Mar0xy** [comment] 2024-06-11 00:25
This could indicate that there could be something wrong with the Castlabs electron version in my opinon. What is your thought about it @Mastermindzh considering that "Error: Failed to install required components" is usually caused by it when it fails to download and extract Widevine CDM

**Comment by crimsonthunder** [comment] 2024-06-17 10:53
It suddenly works for me. No idea why. Nevertheless many thanks!

**Comment by Mastermindzh** [comment] 2024-06-17 11:26
Weird indeed. Thanks @crimsonthunder for confirming.

I couldn't replicate it myself so let's just close the issue.

**Closed by Mastermindzh** 2024-06-17 11:26 UTC
