### ISSUE TITLE
Discord RPC not updating properly

### ISSUE THREAD

**Issue by Mar0xy** [Mastermindzh/tidal-hifi#194] opened 2023-01-20 22:25 UTC
I have realized that if you open a playlist or album that the RPC stops updating the observer/event listener simply doesn't work anymore at that point for some reason.

**Comment by 1nikolas** [comment] 2023-01-23 12:42
I was about to open an issue too about this. It gets stuck on the song being at 0:00 left every other song

**Comment by cat-marin** [comment] 2023-06-26 19:54
I'm still having this issue on 5.3.0 - not sure if the fix for #200 was supposed to fix this as well or not but the problem with playlists does still exist.

**Comment by Mastermindzh** [comment] 2023-06-27 06:16
Not yet. I've been slowly experimenting to find a way to fix this in the meantime but overall time is limited I'm afraid :)

**Comment by Mastermindzh** [comment] 2023-07-23 21:16
Duplicate of: https://github.com/Mastermindzh/tidal-hifi/issues/106

**Closed by Mastermindzh** 2023-07-23 21:16 UTC
Labels: duplicate
