### ISSUE TITLE
White Screen when trying to log in 

### ISSUE THREAD

**Issue by lusch4s** [Mastermindzh/tidal-hifi#439] opened 2024-07-12 06:56 UTC
Getting a white screen when trying to log in.
![tidal error](https://github.com/user-attachments/assets/d1bb8776-4b74-4921-a5d5-1d094d6a4bce)

Os:
Bazzite 40 
KDE Plasma 6.1.1

**Comment by Mastermindzh** [comment] 2024-07-12 07:19
Duplicate of https://github.com/Mastermindzh/tidal-hifi/issues/358

Solution also provided there:

> 
> 
>     * Remove cache (`~/.config/tidal-hifi` by default)
> 
>     * running it with `--no-sandbox` from the CLI.

**Closed by Mastermindzh** 2024-07-12 07:19 UTC
