### ISSUE TITLE
Tidal-Hifi Resampling Audio Output 

### ISSUE THREAD

**Issue by jeremy2330** [Mastermindzh/tidal-hifi#430] opened 2024-07-02 05:33 UTC
Tidal-Hifi is resampling the audio bitrate to the default bitrate that Pipewire is using. ie not matter what quality I choose in pipewire conf settings, I can't get Tidal-Hifi to stop resampling the audio. For example, if I play Marvin Gaye - What's Going on at 192khz, Tidal-Hifi outputs 48khz. I have set up Pipewire so that it does not resample, and so I receive 48khz to my DAC. Whereas if I play Pearl Jam - Dark matter which natively outputs 24 Bit / 48khz, it is sent to Pipewire at 48khz and sounds awesome because it hasn't been resampled. 

Firefox does not do this (however I can't get Max hifi on Firefox). When using Firefox, it outputs the audio rate that Tidal is playing. 

As Tidal-Hifi is based on Chromium (I believe, and this is what pw-top calls it), the problem likely resides there. Here is a more detailed discussion of this issue, but as it applies to Chromium:

https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2828

Ideally if there was the ability to have a .conf file where the audio bitrates could be set, or even better, have an option in the GUI to set these.

Very much appreciate the effort that has gone into creating this software. This one change would make it my go to music player.

**Comment by enzy** [comment] 2024-07-03 17:13
Mine outputs F32LE 2 192000 without a problem (Archlinux, Pipewire). 

Pipewire config `/etc/pipewire/pipewire.conf.d/10-rates.conf`:

```
# Adds more common rates
context.properties = {
    default.clock.allowed-rates = [ 44100 48000 88200 96000 19200 ]
    default.clock.rate = 192000
}
```

**Comment by jeremy2330** [comment] 2024-07-04 03:22
Yes, I can get Tidal-Hifi to output the default rate. 

The issue is if the actual FLAC file is a different rate to the default.clock.rate, Tidal-Hifi resamples the audio to the default.clock.rate

eg if you play a Tidal song that's in 44100, in your case Tidal-Hifi (not Pipewire) will resample the file to 192000. If you run pw-top you will see that +Chromium (that's what it calls Tidal-Hifi) is outputting 192000, even though the FLAC file it's playing is 44100.

In my opinion, the native 44100 output (which I can get from Firefox) sounds significantly better than if it is resampled to a higher rate.

**Comment by masterjg** [comment] 2024-07-14 09:10
Yep, can confirm as I use EasyEffects. If played from firefox I get 44.1khz yet from this app 48khz. I think chromium needs some flag enabled or something within this app.

![image](https://github.com/user-attachments/assets/0ce8b29a-919a-43e7-b36d-062930453d3d)
vs
![image](https://github.com/user-attachments/assets/25976922-5259-4c2c-8d29-1d73230d755e)

And it sounds different when resampled. Please disable resampling...

**Comment by Mastermindzh** [comment] 2024-07-15 07:36
Duplicate of: https://github.com/Mastermindzh/tidal-hifi/issues/266

**Closed by Mastermindzh** 2024-07-15 07:36 UTC
