### ISSUE TITLE
MPRIS shows two controllable players in notifications

### ISSUE THREAD

**Issue by Nyabinary** [Mastermindzh/tidal-hifi#267] opened 2023-08-13 18:54 UTC
![image](https://github.com/Mastermindzh/tidal-hifi/assets/97130632/3fcfa43f-69e0-44eb-bf5e-5d4e01d9afff)
Tested with Wayland support off and with Wayland support on.

**Comment by Mastermindzh** [comment] 2023-08-13 19:41
Duplicate of :
https://github.com/Mastermindzh/tidal-hifi/issues/198

**Closed by Mastermindzh** 2023-08-13 19:41 UTC
Labels: duplicate
