### ISSUE TITLE
Correct bitrate

### ISSUE THREAD

**Issue by Skynet011** [Mastermindzh/tidal-hifi#498] opened 2024-11-05 02:43 UTC
Hello. 
I am on Fedora 41 gnome in flatpak.
I play music with a media player and it picks up the correct bitrate.
With Tidal Hifi it cant seem to do that, it is always at 48000.
Thanks so much.

**Comment by Mar0xy** [comment] 2024-11-06 11:00
Please check closed issues first or search for the issue first before opening an issue with a repeated question/issue.

Duplicate of: https://github.com/Mastermindzh/tidal-hifi/issues/266

**Closed** 2024-11-07 07:51 UTC
