### ISSUE TITLE
mpris metadata strange bug 

### ISSUE THREAD

**Issue by JustAnotherStrange** [Mastermindzh/tidal-hifi#106] opened 2022-02-20 14:18 UTC
I am using rescrobbled for last.fm scrobbling, like it said in the readme. It is working mostly great. Except, when I was scrobbling a song decidedly NOT by the Beach Boys, for the first bit of the song (while I was doing something else) it was fine, but when I went to the album page for Pet Sounds by the Beach Boys (without playing anything, mind you), suddenly the album metadata from mpris changed to the album of which its page I was on, but I was not playing anything from. The rest of the metadata stayed the same.

Screenshot to help with explanation:
![image](https://user-images.githubusercontent.com/64844168/154847060-5f8f07f0-6b57-43a4-ab00-b050a7942fe7.png)
Pretending is a song from the album "Woman on the Internet." 
![image](https://user-images.githubusercontent.com/64844168/154847088-2450e921-f748-4e05-a223-f9869feca4f8.png)
But, when I went to the page for Pet Sounds, suddenly the metadata changed, and then it scrobbled the song twice, once with the correct album, and once with the Pet Sounds album. Super strange

Here is the metadata for the `tidal-hifi` mpris player and for the chromium.instanceXXXXX player:
![image](https://user-images.githubusercontent.com/64844168/154847342-49ff47b2-1bc0-4526-b4d1-bcc7345c154c.png)
The album art link still goes to the right album art. This leads me to believe that there is something wrong with the way that it fetches the album title for the metadata.

Thanks for the nice work on making Tidal on Linux a much better experience. I'm running the latest version installed from the `tidal-hifi` AUR package, I just updated to make sure.

Thanks!!

**Comment by Mastermindzh** [comment] 2022-08-07 09:32
I'll be working on tidal-hifi today so I'll see if I can get your bug to reproduce.

**Comment by Mastermindzh** [comment] 2022-08-07 14:00
Hey, 

Tidal doesn't display the **album** that a song belongs to anywhere on the UI so we can't really get it.
Right now we're using a bit of a dirty hack that takes the album from the "album view" page...

As you've discovered though, if you change albums in the main page (instead of the bottom player bar) it will get the wrong album.

The only fix I can think of is to use the "playing from" text instead, but that would show playlists, artists, albums, etc...
For reference, I played "for evigt" and then switched to a random song, but Tidal still shows "playing from For evigt"

![image](https://user-images.githubusercontent.com/4190290/183294429-9ea89a6b-2a02-484b-8ac1-8e320a03a947.png)

**Comment by JustAnotherStrange** [comment] 2022-08-09 22:47
Thanks for your work. 

I have just been using it in the browser with a [web scrobbler chromium extension,](https://github.com/web-scrobbler/web-scrobbler) which (curiously) has been working great. 

I don't know Javascript, but for those who do, it might be interesting to see how web-scrobbler manages to accurately grab the album info. Maybe the way it's done there could be integrated into this program. Here is the tidal module for those interested.
https://github.com/web-scrobbler/web-scrobbler/blob/fdc293973691fd92679276b1fd5f9437b0430b8b/src/connectors/tidal.js

**Comment by Mastermindzh** [comment] 2022-08-10 08:20
Maybe we can... But a quick look makes it appear that they use nowplaying:

`#nowPlaying div.react-tabs a[href^="/album/"]`

I don't know what those react-tabs with a href would provide, I'd think it's a URL but I can have a look at that.

**Comment by BlueManCZ** [comment] 2022-09-16 15:57
Well, I had a look at this and it is the same issue. It works only if you play a song directly from the album. If you then skip to the recommendations from the mix, you don't even get the element, but `null`.

You can test this in the console.
```
document.querySelector("#nowPlaying div.react-tabs a[href^='/album/']").innerText; 
```

**Comment by zoli111** [comment] 2022-11-05 18:48
I tested Tidal Hi-Fi, Chromium and Firefox with the web player. I found that with Tidal Hi-Fi or Chromium playing playerctl does not show the album or shows an empty string for it, but with Firefox it works normally.

I don't know what does Firefox differently, but it shows that this should be possible somehow.

**Comment by Mastermindzh** [comment] 2023-07-23 21:27
This actually seems to be fixed in the next release but is prone to breaking again.
I will work on a better solution soon. But for now, enjoy the updates in playlists and albums 😄

**Closed** 2023-07-24 21:10 UTC
Labels: bug, Available in next release
